name: jme

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas
  - h5py
  - jupyter-book=0.12
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - rasterio
  - scipy
  - seaborn
  - sphinx=4.3.2
  - black